#!/usr/bin/env bash

set -euxo pipefail

commits_count=$(curl -H 'Accept: application/vnd.github+json' \
    https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${PULL_NUMBER}) \
    jq '.commits'

if [[ ${commits_count} != 1 ]]; then
    echo '
    All PRs must contain a single commit.
    Please refer to https://github.com/kubernetes-sigs/kernel-module-management/blob/main/CONTRIBUTING.md
    '
    exit 1
fi
