#!/usr/bin/env bash

set -euxo pipefail

pr=$(curl -H 'Accept: application/vnd.github+json' \
    https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${PULL_NUMBER})

pr_title=$(echo ${pr} | jq -r '.title')
# Github UI adds '^M' (which is interpreted as '\r' by the 'sed' command) at the end of lines.
pr_body=$(echo ${pr} | jq -r '.body' | sed 's/\r$//g')

# We assume there is a single commit in each PR
pr=$(curl -H 'Accept: application/vnd.github+json' \
    https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls/${PULL_NUMBER}/commits \
    | jq -r '.[0].commit.message'])
commit_subject=$(echo ${commit} | jq -r '.message' | head -n 1)
commit_body=$(echo ${commit} | jq -r '.message' | tail -n +3)


if [[ ${pr_title} != ${commit_subject} ]] ; then
    echo "
    Commit and PR are out of sync. Make sure the following are identical:
        * PR title   <-->    commit subject
    "
    exit 1
fi

if [[ ${pr_body} != ${commit_body} ]] ; then
    echo "
    Commit and PR are out of sync. Make sure the following are identical:
        * PR body    <-->    commit body
    "
    exit 1
fi
