{{- /*gotype: github.com/rh-ecosystem-edge/kernel-module-management/internal/sign/pod.TemplateData */ -}}
FROM {{ .SignImage }} AS signimage

FROM {{ .UnsignedImage }} as source

COPY --from=signimage /usr/local/bin/sign-file /usr/local/bin/sign-file

{{ range .FilesToSign }}
RUN for file in {{ . }}; do \
        /usr/local/bin/sign-file sha256 /run/secrets/key/key.pem /run/secrets/cert/cert.pem ${file}; \
    done
{{- end }}
